# ============================================================
# SkillHub Backend - Configuration SonarCloud
# ============================================================

sonar.projectKey=Nirina2108_skillhub-back_CICD
sonar.organization=nirina2108

sonar.sources=app/
sonar.tests=tests/

sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=vendor/**,node_modules/**,public/**
